#name: Build & Deploy Spring app
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build-deploy:
#    name: Build and Deploy Spring Boot for Beginners
#    runs-on: ubuntu-latest
#    env:
#      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: 17
#
#      - name: Run Unit Tests
#        run: mvn -B test --file pom.xml
#
#      - name: Build the application
#        run: |
#          mvn clean
#          mvn -B package --file pom.xml
#
#      - name: Get timestamp
#        id: timestamp
#        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
#
#      - name: Build Docker image (no push)
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push Docker image
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.tag }}



name: Build & Deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:$(date +'%Y%m%d%H%M%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:$(date +'%Y%m%d%H%M%S')











































#name: Build & Deploy Spring app
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build-deploy:
#    name: Build and Deploy Spring boot for beginner
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: 17
#
#      - name: Unit Tests
#        run: mvn -B test --file pom.xml
#
#      - name: Build the application
#        run: |
#          mvn clean
#          mvn -B package --file pom.xml
#
#      - name: Build Docker Image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:today
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:today